In [1]:
# Базовый вывод и ввод
print("Привет!")
name = input("Как тебя зовут? ")
print("Успешной учёбы, ", name)
age = input("Сколько тебе лет? ")
print(age, "? ", "Понятно,", name)

# Программа-опрос с целыми числами
print("\nОтветь на пару вопросов целыми числами:")
q1 = int(input("Сколько часов в день ты спишь? "))
if q1 < 6:
    print("Это слишком мало, нужно высыпаться!")
elif q1 > 10:
    print("Ого, ты что, сурок?")
else:
    print("Отличный режим сна!")

q2 = int(input("В каком году ты поступил в вуз? "))
print("Ты учишься уже", 2026 - q2, "лет/года.")

Привет!


Как тебя зовут?  Глеб


Успешной учёбы,  Глеб


Сколько тебе лет?  18


18 ?  Понятно, Глеб

Ответь на пару вопросов целыми числами:


Сколько часов в день ты спишь?  8


Отличный режим сна!


В каком году ты поступил в вуз?  2025


Ты учишься уже 1 лет/года.


In [2]:
import numpy as np

# 1. Арифметические операции
mas1 = np.array([34, 45, 56, 0, -1])
mas2 = np.array([10, 20, 30, 40, 50])
print("Сложение:", mas1 + mas2)
print("Вычитание:", mas1 - mas2)
print("Умножение:", mas1 * mas2)

# 2. Разные типы данных
print("\nВещественные:", np.array([1.5, 2.5]) + np.array([0.5, 1.0]))
print("Комплексные:", np.array([1+2j, 3+4j]) + np.array([1+2j, 3+4j]))
# Строки лучше делать обычными списками Python, без np.array
s_mas1 = ['Привет', 'мир']
s_mas2 = [', ', '!']
print("Строковые (сложение):", s_mas1[0] + s_mas2[0] + s_mas1[1] + s_mas2[1])

# 3. Тригонометрические функции
x1 = np.array([0.0, 1.0, 2.0])
x2 = np.array([0.5, 1.5, 2.5])
print("\nТригонометрия (sin+cos):", np.sin(x1) + np.cos(x2))

# 4. Массивы нулей и единиц
print("Массив из 6 нулей:", np.zeros(6, dtype=int))
print("Массив из 20 единиц:", np.ones(20, dtype=int))

# 5. Индексация
A = np.array([5, -3, 12, -8, 0, 7, -1, 4])
print("\nМассив A в обратном порядке:", A[::-1])
print("Сумма положительных элементов A:", np.sum(A[A > 0]))

# Месяцы
months = ["январь", "февраль", "март", "апрель", "май", "июнь",
          "июль", "август", "сентябрь", "октябрь", "ноябрь", "декабрь"]
print("Весенние месяцы:", months[2], months[3], months[4])

Сложение: [44 65 86 40 49]
Вычитание: [ 24  25  26 -40 -51]
Умножение: [ 340  900 1680    0  -50]

Вещественные: [2.  3.5]
Комплексные: [2.+4.j 6.+8.j]
Строковые (сложение): Привет, мир!

Тригонометрия (sin+cos): [0.87758256 0.91220819 0.10815381]
Массив из 6 нулей: [0 0 0 0 0 0]
Массив из 20 единиц: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Массив A в обратном порядке: [ 4 -1  7  0 -8 12 -3  5]
Сумма положительных элементов A: 28
Весенние месяцы: март апрель май


In [3]:
import numpy as np

n = 30
np.random.seed(42) # Фиксируем случайные числа

# 1. Данные за 30 дней
vylet = np.random.randint(5, 20, n)
prilet = np.random.randint(5, 20, n)
print("Вылеты:", vylet)
print("Прилеты:", prilet)

# 2. Общее количество рейсов
total = vylet + prilet
print("Всего рейсов за каждый день:", total)

# 3. Минимумы и максимумы
print("\nМакс. вылетов:", np.max(vylet), " Мин. вылетов:", np.min(vylet))
print("Макс. прилетов:", np.max(prilet), " Мин. прилетов:", np.min(prilet))
print("Макс. всего:", np.max(total), " Мин. всего:", np.min(total))

# 4. Статистика
print("\nСтатистика по всем рейсам (total):")
print("Среднее:", np.mean(total))
print("Медиана:", np.median(total))
print("Дисперсия:", np.var(total))
print("Стандартное отклонение:", np.std(total))

# 5. В какую половину месяца было больше рейсов
half1 = np.sum(total[0:15])
half2 = np.sum(total[15:30])
if half1 > half2:
    print("\nВ первой половине месяца рейсов было больше (", half1, ">", half2, ")")
else:
    print("\nВо второй половине месяца рейсов было больше (", half2, ">", half1, ")")

# 6. Прилеты для суббот
# (1-й день понедельник имеет индекс 0, значит суббота имеет индекс 5. Шаг 7 дней)
print("\nПрилеты в субботы (дни 6, 13, 20, 27):", prilet[5::7])

# 7. Фильтрация вылетов
print("Дни, когда вылетов больше 10:", vylet[vylet > 10])
print("Дни, когда вылетов больше 10, но меньше 50:", vylet[(vylet > 10) & (vylet < 50)])

Вылеты: [11  8 17 19 15 12 17  9 11 14  7 11 15 15 12  9  8 12 12  7 10  9  6 12
 16 18 10  6 16  9]
Прилеты: [ 5 16 14 10 17 16 13  5 15 15 19 14 16 16 19 18 18 19 18  7 16 11  8 13
  7  9  7 11  9 13]
Всего рейсов за каждый день: [16 24 31 29 32 28 30 14 26 29 26 25 31 31 31 27 26 31 30 14 26 20 14 25
 23 27 17 17 25 22]

Макс. вылетов: 19  Мин. вылетов: 6
Макс. прилетов: 19  Мин. прилетов: 5
Макс. всего: 32  Мин. всего: 14

Статистика по всем рейсам (total):
Среднее: 24.9
Медиана: 26.0
Дисперсия: 31.423333333333336
Стандартное отклонение: 5.605651909754417

В первой половине месяца рейсов было больше ( 403 > 344 )

Прилеты в субботы (дни 6, 13, 20, 27): [16 16  7  7]
Дни, когда вылетов больше 10: [11 17 19 15 12 17 11 14 11 15 15 12 12 12 12 16 18 16]
Дни, когда вылетов больше 10, но меньше 50: [11 17 19 15 12 17 11 14 11 15 15 12 12 12 12 16 18 16]


In [4]:
import numpy as np

# 1. Создаем матрицу A 4x4 со случайными числами от 1 до 10
A = np.random.randint(1, 11, (4, 4))
print("Матрица A:\n", A)

# 2. Сумма четных элементов
print("\nСумма четных элементов A:", np.sum(A[A % 2 == 0]))

# 3. Вычисляем матрицы (T транспонирование, -1 обратная матрица)
A_T = A.T
A_inv = np.linalg.inv(A)
print("\nТранспонированная матрица A^T:\n", A_T)
print("\nОбратная матрица A^(-1):\n", np.round(A_inv, 4))

# 4. Находим определитель матрицы A (округляем для красивого вывода)
det_A = np.linalg.det(A)
print("\nОпределитель матрицы A:", round(det_A, 4))

# 5. Для матрицы A строим матрицу миноров M
M = np.zeros((4, 4)) # Создаем пустую матрицу 4x4
for i in range(4): # Идем по строкам
    for j in range(4): # Идем по столбцам
        # Вычеркиваем i-ю строку (axis=0) и j-й столбец (axis=1) из матрицы А
        temp = np.delete(A, i, axis=0)
        temp = np.delete(temp, j, axis=1)
        # Считаем определитель оставшейся части и округляем
        M[i, j] = round(np.linalg.det(temp), 4)

print("\nМатрица миноров M (для матрицы A):\n", M)

Матрица A:
 [[ 7  2  4  9]
 [ 2 10  9 10]
 [ 5  2  4  7]
 [ 8  3  1  4]]

Сумма четных элементов A: 46

Транспонированная матрица A^T:
 [[ 7  2  5  8]
 [ 2 10  2  3]
 [ 4  9  4  1]
 [ 9 10  7  4]]

Обратная матрица A^(-1):
 [[-0.3993 -0.0746  0.5261  0.1642]
 [ 0.2687  0.1343 -0.597   0.1045]
 [-1.209  -0.1045  1.6866  0.0299]
 [ 0.8993  0.0746 -1.0261 -0.1642]]

Определитель матрицы A: -268.0

Матрица миноров M (для матрицы A):
 [[ 107.   72.  324.  241.]
 [ -20.  -36.  -28.  -20.]
 [-141. -160. -452. -275.]
 [  44.  -28.    8.   44.]]


In [5]:
import numpy as np

n = 30
np.random.seed(42) # Те же самые числа, что и в предыдущей ячейке

# 1. Данные за 30 дней
vylet = np.random.randint(5, 20, n)
prilet = np.random.randint(5, 20, n)

# Объединяем в двумерный массив (30 строк, 2 столбца)
airport = np.column_stack((vylet, prilet))
print("Массив (Вылет, Прилет):\n", airport)

# 2. Добавляем третий столбец (общее количество рейсов)
total = airport[:, 0] + airport[:, 1]
# Добавляем total как новый (третий) столбец к матрице airport
airport = np.column_stack((airport, total))
print("\nМассив с третьим столбцом (Вылет, Прилет, Всего):\n", airport)

# 3. Минимумы и максимумы для всех трёх показателей (по столбцам, axis=0)
print("\nМаксимумы по столбцам (Вылет, Прилет, Всего):", np.max(airport, axis=0))
print("Минимумы по столбцам (Вылет, Прилет, Всего):", np.min(airport, axis=0))

# 4. Оценить средние, медианы, дисперсии, отклонения (для 3-го столбца)
print("\nСтатистика по 3-му столбцу (Всего):")
print("Среднее:", np.mean(airport[:, 2]))
print("Медиана:", np.median(airport[:, 2]))
print("Дисперсия:", np.var(airport[:, 2]))
print("Стандартное отклонение:", np.std(airport[:, 2]))

# 5. В какую половину месяца было больше суммарное количество рейсов
half1 = np.sum(airport[0:15, 2])
half2 = np.sum(airport[15:30, 2])

if half1 > half2:
    print("\nВ первой половине месяца рейсов было больше (", half1, ">", half2, ")")
else:
    print("\nВо второй половине месяца рейсов было больше (", half2, ">", half1, ")")

# 6. Распечатать количество прилетов для суббот (используем срез)
print("\nПрилеты в субботы:", airport[5::7, 1])

# 7. Распечатать данные о ВЫЛЕТАХ (границы можно скорректировать)
vylet_col = airport[:, 0]

# когда их было больше 10
print("\nДни, когда вылетов больше 10:", vylet_col[vylet_col > 10])

# когда их было больше 10, но меньше 50
print("Дни, когда вылетов больше 10, но меньше 50:", vylet_col[(vylet_col > 10) & (vylet_col < 50)])

Массив (Вылет, Прилет):
 [[11  5]
 [ 8 16]
 [17 14]
 [19 10]
 [15 17]
 [12 16]
 [17 13]
 [ 9  5]
 [11 15]
 [14 15]
 [ 7 19]
 [11 14]
 [15 16]
 [15 16]
 [12 19]
 [ 9 18]
 [ 8 18]
 [12 19]
 [12 18]
 [ 7  7]
 [10 16]
 [ 9 11]
 [ 6  8]
 [12 13]
 [16  7]
 [18  9]
 [10  7]
 [ 6 11]
 [16  9]
 [ 9 13]]

Массив с третьим столбцом (Вылет, Прилет, Всего):
 [[11  5 16]
 [ 8 16 24]
 [17 14 31]
 [19 10 29]
 [15 17 32]
 [12 16 28]
 [17 13 30]
 [ 9  5 14]
 [11 15 26]
 [14 15 29]
 [ 7 19 26]
 [11 14 25]
 [15 16 31]
 [15 16 31]
 [12 19 31]
 [ 9 18 27]
 [ 8 18 26]
 [12 19 31]
 [12 18 30]
 [ 7  7 14]
 [10 16 26]
 [ 9 11 20]
 [ 6  8 14]
 [12 13 25]
 [16  7 23]
 [18  9 27]
 [10  7 17]
 [ 6 11 17]
 [16  9 25]
 [ 9 13 22]]

Максимумы по столбцам (Вылет, Прилет, Всего): [19 19 32]
Минимумы по столбцам (Вылет, Прилет, Всего): [ 6  5 14]

Статистика по 3-му столбцу (Всего):
Среднее: 24.9
Медиана: 26.0
Дисперсия: 31.423333333333336
Стандартное отклонение: 5.605651909754417

В первой половине месяца рейсов было бо